baseURL: "http://tecnologiaequidade.org.br"
defaultContentLanguage: pt
languageCode:    "pt-br"
disableKinds:    ["taxonomy", "taxonomyTerm", "RSS"]
enableRobotsTXT: true
metaDataFormat:  "yaml"
enableMissingTranslationPlaceholders: true
disableFastRender: true
ignoreFiles: [ "\\.tmp$", "\\.tmp\\-browserify" ]
stepAnalysis: true
templateMetrics: true
pluralizeListTitles: false
googleAnalytics: "UA-117128393-1"
FootnoteReturnLinkContents: "↩"

taxonomies:
  role: "role"

languages:
  pt:
    contentDir: content/portuguese
    languageName: Português
    languageCode: "pt-br"
    title: "Instituto Tecnologia & Equidade"
    weight: 1
    params:
      description: O Instituto Tecnologia e Equidade é uma organização sem fins lucrativos que desenvolve pesquisas e projetos experimentais que contribuem para alcançar a equidade com o uso ético da tecnologia.
      subtitle: "Sistema de Avaliação e Gestão Unificado de Informações"
    ids:
        - Manifesto: "manifesto"
          Projetos: "projetos"
          O-que-fazemos: "o-que-fazemos"
          Valores: "valores"
          Conselheiros: "conselheiros"
    menu:
      main:
          - Name: "Manifesto"
            Pre: ""
            Weight: 1
            Identifier: "manifesto"
            URL: "#manifesto"
          - Name: "Projetos"
            Pre: ""
            Weight: 2
            Identifier: "projetos"
            URL: "#projetos"
          - Name: "O que fazemos"
            Pre: ""
            Weight: 3
            Identifier: "o-que-fazemos"
            URL: "#o-que-fazemos"
          - Name: "Valores"
            Pre: ""
            Weight: 4
            Identifier: "valores"
            URL: "#valores"
          - Name: "Conselheiros"
            Pre: ""
            Weight: 5
            Identifier: "conselheiros"
            URL: "#conselheiros"

  en:
    contentDir: content/english
    languageName: English
    languageCode: "en-US"
    title: "The Technology & Equity Institute (T&EI)"
    weight: 2
    params:
      description: Is a non-profit organization that develops research and experimental projects that contribute to achieving equity with the ethical use of technology.
      subtitle: "The Technology & Equity Institute (T&EI)"
    ids:
        - Manifesto: "manifesto"
          Projetos: "projects"
          O-que-fazemos: "what-we-do"
          Valores: "values"
          Conselheiros: "counselors"
    menu:
      main:
          - Name: "Manifesto"
            Pre: ""
            Weight: 1
            Identifier: "manifesto"
            URL: "#manifesto"
          - Name: "Projetos"
            Pre: ""
            Weight: 2
            Identifier: "projetos"
            URL: "#projetos"
          - Name: "O que fazemos"
            Pre: ""
            Weight: 3
            Identifier: "o-que-fazemos"
            URL: "#what-we-do"
          - Name: "Valores"
            Pre: ""
            Weight: 4
            Identifier: "valores"
/            URL: "#values"
          - Name: "Conselheiros"
            Pre: ""
            Weight: 5
            Identifier: "conselheiros"
            URL: "#couselors"
  es:
    contentDir: content/espanol
    languageName: Español
    languageCode: "es-MX"
    alt: "es-MX"
    title: "Hola"
    weight: 3
    params:
      description: El instituto.
      subtitle: "Holla"
    ids:
        - Manifesto: "manifesto"
          Projetos: "projects"
          O-que-fazemos: "what-we-do"
          Valores: "values"
          Conselheiros: "counselors"
    menu:
      main:
          - Name: "Manifesto"
            Pre: ""
            Weight: 1
            Identifier: "manifesto"
            URL: "#manifesto"
          - Name: "Projetos"
            Pre: ""
            Weight: 2
            Identifier: "projetos"
            URL: "#projetos"
          - Name: "O que fazemos"
            Pre: ""
            Weight: 3
            Identifier: "o-que-fazemos"
            URL: "#o-que-fazemos"
          - Name: "Valores"
            Pre: ""
            Weight: 4
            Identifier: "valores"
            URL: "#valores"
          - Name: "Conselheiros"
            Pre: ""
            Weight: 5
            Identifier: "conselheiros"
            URL: "#conselheiros"

params:
  authorName:    "tecnologiaequidade"
  gitHubUser:    "tecnologiaequidade"

  author:
    IT&E:
      name: "IT & Equidade"
      link: "http://tecnologiaequidade.org.br"
      logo: "IT&E.png"

