baseURL: "https://tecnologiaequidade.org.br"
defaultContentLanguage: pt
languageCode:    "pt-br"
disableKinds:    ["taxonomy", "taxonomyTerm", "RSS"]
enableRobotsTXT: true
metaDataFormat:  "yaml"
enableMissingTranslationPlaceholders: true
disableFastRender: true
ignoreFiles: [ "\\.tmp$", "\\.tmp\\-browserify" ]
stepAnalysis: true
templateMetrics: true
pluralizeListTitles: false
googleAnalytics: "UA-117128393-1"
FootnoteReturnLinkContents: "↩"

taxonomies:
  role: "role"

languages:
  pt:
    contentDir: content/portuguese
    languageName: Português
    languageCode: "pt-br"
    title: "Instituto Tecnologia & Equidade"
    weight: 1
    params:
      description: "O Instituto Tecnologia e Equidade é uma organização sem fins lucrativos que desenvolve pesquisas e projetos experimentais que contribuem para alcançar a equidade com o uso ético da tecnologia."
      subtitle: "Instituto Tecnologia & Equidade"
    menu:
      main:
          - Name: "Manifesto"
            Pre: ""
            Weight: 1
            Identifier: "manifesto"
            URL: "#manifesto"
          - Name: "Projetos"
            Pre: ""
            Weight: 2
            Identifier: "projects"
            URL: "#projects"
          - Name: "Metodologia"
            Pre: ""
            Weight: 3
            Identifier: "methodology"
            URL: "#methodology"
          - Name: "O que fazemos"
            Pre: ""
            Weight: 4
            Identifier: "o-que-fazemos"
            URL: "#what-we-do"
          - Name: "Valores"
            Pre: ""
            Weight: 5
            Identifier: "valores"
            URL: "#values"
          - Name: "Conselheiros"
            Pre: ""
            Weight: 6
            Identifier: "conselheiros"
            URL: "#counselors"
  en:
    contentDir: content/english
    languageName: English
    languageCode: "en-US"
    title: "The Technology & Equity Institute (T&EI)"
    weight: 2
    params:
      description: "Is a non-profit organization that develops research and experimental projects that contribute to achieving equity with the ethical use of technology."
      subtitle: "The Technology & Equity Institute (T&EI)"
    menu:
      main:
          - Name: "Manifesto"
            Pre: ""
            Weight: 1
            Identifier: "manifesto"
            URL: "#manifesto"
          - Name: "Projects"
            Pre: ""
            Weight: 2
            Identifier: "projects"
            URL: "#projects"
          - Name: "Methodology"
            Pre: ""
            Weight: 3
            Identifier: "methodology"
            URL: "#methodology"
          - Name: "What we do"
            Pre: ""
            Weight: 4
            Identifier: "what-we-do"
            URL: "#what-we-do"
          - Name: "Values"
            Pre: ""
            Weight: 5
            Identifier: "mission-vision-values"
            URL: "#values"
          - Name: "Counselors"
            Pre: ""
            Weight: 6
            Identifier: "counselors"
            URL: "#counselors"
  es:
    contentDir: content/espanol
    languageName: Español
    languageCode: "es-ar"
    title: "Instituto Tecnología y Equidad"
    weight: 3
    params:
      description: "El Instituto Tecnologia y Equidad es una organización sin fines de lucro que desarrolla investigaciones y proyectos experimentales que contribuyen para alcanzar la equidad con el uso ético de la tecnología."
      subtitle: "Instituto Tecnología y Equidad"
    menu:
      main:
          - Name: "Manifiesto"
            Pre: ""
            Weight: 1
            Identifier: "manifiesto"
            URL: "#manifesto"
          - Name: "Proyectos"
            Pre: ""
            Weight: 2
            Identifier: "proyectos"
            URL: "#projects"
          - Name: "Metodología"
            Pre: ""
            Weight: 3
            Identifier: "methodology"
            URL: "#methodology"
          - Name: "Qué hacemos?"
            Pre: ""
            Weight: 4
            Identifier: "que-hacemos"
            URL: "#what-we-do"
          - Name: "Valores"
            Pre: ""
            Weight: 5
            Identifier: "mision-vision-valores"
            URL: "#values"
          - Name: "Consejeros"
            Pre: ""
            Weight: 6
            Identifier: "consejeros"
            URL: "#counselors"

params:
  authorName:    "tecnologiaequidade"
  gitHubUser:    "tecnologiaequidade"

  author:
    IT&E:
      name: "IT & Equidade"
      link: "http://tecnologiaequidade.org.br"
      logo: "IT&E.png"

params:
  shareImages:
    default: "assets/images/compartilhamento.jpg"
    twitter: "assets/images/twitter-compartilhamento.jpg"
    facebook: "assets/images/facebook-compartilhamento.jpg"
