backend:
  name: tecnologiaequidade.github.io
  branch: develop
  accept_roles:
    - admin
    - editor

publish_mode: editorial_workflow
media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/imagens" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "projetos"
    label: "projetos"
    folder: "content/projetos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Date", name: "date", widget: "datetime", format: "DD-MM-YYYY hh:mma"}
      - {label: "Draft", name: "draft", widget: "string", default: "true"}
      - {label: "Url", name: "url", widget: "string", default: "/projetos/"}
      - {label: "image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Projetos Relacionados", name: "relatedProjects", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
