backend:
  name: github
  repo: tecnologiaequidade/tecnologiaequidade.github.io # Path to your Github repository
  branch: develop
  accept_roles:
    - admin
    - editor
publish_mode: editorial_workflow
media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/imagens" # The src attribute for uploaded media will begin with /images/uploads
collections:
  -
    name: "projects"
    label: "projetos"
    folder: "content/projetos"
    create: true
    slug: "{{slug}}"
    fields:
      -
        label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-DD-MMThh:mm:ssZ" # date sample 2018-03-06T14:48:47-03:00
      -
        label: "Title"
        name: "title"
        widget: "string"
        tagname: "h1"
        pattern: ['.{3,40}', "Must have between 3 and 40 characters"]
      -
        label: "Subtitle"
        name: "subtitle"
        widget: "string"
        tagname: "h1"
        pattern: ['.{0,40}', "Must have between 0 and 40 characters"]
      -
        label: "Title Image"
        name: "titleImage"
        widget: "image"
        required: false
        tagname: ""
      -
        label: "Dark Text"
        name: "darkText"
        widget: "boolean"
        default: "true"
      -
        label: "Draft"
        name: "draft"
        widget: "boolean"
        default: "true"
      -
        label: "Url"
        name: "url"
        widget: "string"
        default: "/projetos/"
      -
        label: "Summary"
        name: "summary"
        widget: "text"
      -
        label: "Image"
        name: "image"
        widget: "object"
        fields:
          - {image: "", caption: "", widget: "string"}
      -
        label: "Weight"
        name: "weight"
        widget: "number"
        valueType: "int"
      -
        label: "Body"
        name: "body"
        widget: "markdown"
  -
    name: "authors"
    label: "Authors"
    files: "data/authors.yml"
    fields:
      -
        label: "name"
        name: "name"
        widget: "string"
      -
        label: "slug"
        name: "slug"
        widget: "string"
      -
        label: "image"
        name: "image"
        widget: "image"
      -
        label: "about"
        name: "about"
        widget: "text"
      -
        label: "weight"
        name: "weight"
        widget: "number"
  -
    name: "projectsList"
    label: "Projects list"
    files: "data/projectsList.yml"
    fields:
      -
        label: "projectName"
        name: "projectName"
        widget: "string"
      -
        label: "slug"
        name: "slug"
        widget: "string"
      -
        label: "projectUrl"
        name: "slug"
        widget: "slug"
      -
        label: "weight"
        name: "weight"
        widget: "number"
